### ISSUE TITLE
Godot QR Code

### ISSUE THREAD

**Issue by br-it0** [thiagobruno/godot3.2_compilarmodulo#3]
Fala Thiagão beleza? Então estou tendo um problema com o módulo ao tentar scanear um Qr Code, consigo tirar a foto, porém quando quando aperto a confirmação na câmera, me parece que ela não está carregando no aplicativo, estou com as permissões ok!
Sabe o que poderia ser?

**Comment by thrbr84** [comment]
Opa tudo beleza? Atualizei na master uma atualização migrando as bibliotecas que estava usando para uma versão mais recente! Obrigado por abrir essa issue!
